import Link from 'next/link'
import type { Metadata } from 'next'
import { ArrowRight, LockKeyhole, ScanSearch, SlidersHorizontal, ShieldCheck } from 'lucide-react'
import { Reveal } from '@/components/reveal'
import { SITE } from '@/lib/content/site'
export const metadata:Metadata={title:'Capital, organized around you',description:SITE.description,alternates:{canonical:'/'}}
const states=['Provider not connected','Observed allocation unavailable','Authorization unavailable','Backend required','No transaction history']
export default function HomePage(){return <>
<section className="hero"><div className="hero-field" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="hero-glow"/></div><div className="hero-inner"><p className="eyebrow">Capital operating infrastructure</p><h1>Capital, organized<br/>around you.</h1><p className="hero-copy">Neptlium unifies portfolio intelligence, digital assets, allocation modeling, controlled capital operations and long-term capital organization in one operating environment.</p><div className="hero-actions"><a className="button" href={SITE.accessUrl}>Access Neptlium <ArrowRight/></a><Link className="text-link" href="/platform">Explore the platform <ArrowRight/></Link></div></div><div className="hero-note">Observe clearly. Model deliberately. Authorize explicitly.</div></section>
<section className="section"><Reveal><div className="section-lead"><p className="eyebrow">Operating environment</p><h2>One coherent view of modern ownership.</h2><p>Bring fragmented capital context into a controlled workspace designed around understanding first and action only when infrastructure permits.</p></div></Reveal><Reveal className="interface"><div className="interface-top"><span>Capital overview</span><span className="status">Illustrative interface</span></div><div className="interface-grid"><div className="visual-panel"><div className="radar"><span/></div><p>Portfolio intelligence</p><small>Provider-dependent data</small></div><div className="capability-list">{['Digital asset infrastructure','Allocation modeling','Treasury organization','Controlled capital operations'].map((x,i)=><div key={x}><span>0{i+1}</span><p>{x}</p><small>{i===1?'Modeling only':'Backend required'}</small></div>)}</div></div></Reveal></section>
<section className="section steps"><Reveal><div className="section-lead"><p className="eyebrow">Decision architecture</p><h2>Observe. Model. Authorize.</h2></div></Reveal><div className="step-grid">{[[ScanSearch,'Observe','Understand holdings, exposure and structure through connected, verified sources.'],[SlidersHorizontal,'Model','Explore allocation scenarios without initiating any capital movement.'],[LockKeyhole,'Authorize','Move from intent to explicit approval only when custody, ledger, security and execution infrastructure exists.']].map(([Icon,title,body],i)=><Reveal key={String(title)}><article><span>0{i+1}</span><Icon/><h3>{String(title)}</h3><p>{String(body)}</p>{i===1&&<strong>Modeling does not move capital.</strong>}{i===2&&<strong>Infrastructure-dependent · unavailable</strong>}</article></Reveal>)}</div></section>
<section className="section universe"><Reveal><div className="section-lead"><p className="eyebrow">Capital Universe</p><h2>A focused digital-asset foundation.</h2><p>Planned support is provider-dependent and is not currently represented as live or production-supported.</p></div></Reveal><div className="asset-row">{[['USDC','Base'],['ETH','Base'],['BTC','Bitcoin']].map(([asset,network])=><Reveal key={asset}><div><span>{asset}</span><p>{network}</p><small>Planned · provider-dependent</small></div></Reveal>)}</div></section>
<section className="section security-block"><Reveal><div className="section-lead"><p className="eyebrow">Security and control</p><h2>Control is part of the architecture.</h2></div></Reveal><div className="control-grid">{['Explicit authorization','Role-aware access','Auditability','Provider verification','Controlled execution','Secure infrastructure boundaries'].map(x=><Reveal key={x}><div><ShieldCheck/><span>{x}</span></div></Reveal>)}</div><p className="qualifier">These are product and infrastructure principles, not claims of certification or regulatory approval.</p></section>
<section className="section product-stage"><Reveal><div className="section-lead"><p className="eyebrow">Product experience</p><h2>Truthful states. Deliberate transitions.</h2></div></Reveal><div className="stage-shell"><div className="stage-rail"><span>Workspace / Overview</span><span className="status">Demonstration only</span></div><div className="stage-body"><div className="empty-visual"><div/><p>Connect verified infrastructure to observe capital.</p></div><ul>{states.map(x=><li key={x}><span/>{x}</li>)}</ul></div></div></section>
<section className="final-cta"><Reveal><p className="eyebrow">Neptlium</p><h2>Bring capital into focus.</h2><p>Enter the operating environment for modern ownership.</p><a className="button" href={SITE.accessUrl}>Access Neptlium <ArrowRight/></a></Reveal></section>
</>}

