import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { PRODUCTS, SOLUTIONS } from '@/lib/content/public-architecture';
import { SITE } from '@/lib/content/site';
import { createPageMetadata } from '@/lib/seo';
export const metadata=createPageMetadata({title:'The Operating System for Capital',description:'Neptlium is a capital operating platform for portfolio context, treasury, allocation, capital movement, governance and intelligence.',path:'/'});
const capitalState=['Portfolio context','Liquidity & treasury','Capital account'] as const;
const operatingCore=['Observe','Understand','Govern'] as const;
const governedWork=['Treasury coordination','Allocation workflows','Portfolio intelligence'] as const;
const trustLayers=[['Evidence','Preserve whether information is observed, provider-reported, derived, modeled or authoritative.'],['Governance','Keep identity, review, permission and consequential authority visible around sensitive capital work.'],['State','Distinguish proposed, reviewed, authorized, submitted, settled and reconciled outcomes rather than collapsing the lifecycle.']] as const;
export default function HomePage(){return <div className="neptlium-home"><section className="authority-hero" aria-labelledby="home-hero-title"><div className="web-shell authority-hero-inner"><div className="authority-hero-copy"><p className="web-eyebrow">Capital operating infrastructure</p><h1 id="home-hero-title">The operating system for capital.</h1><p className="authority-hero-lead">See, coordinate and govern capital across treasury, allocation and portfolio context.</p><div className="authority-actions"><Link className="web-button primary" href={SITE.publicAccessUrl}>{SITE.publicAccessLabel} <ArrowRight aria-hidden="true" /></Link><Link className="text-arrow-link on-dark" href="/platform">Explore platform <ArrowRight aria-hidden="true" /></Link></div></div><div className="hero-architecture" aria-label="Illustrative Neptlium capital operating architecture"><section className="hero-architecture-plane"><span className="hero-architecture-kicker">01 / Capital state</span><h2>Establish what is known.</h2><ul>{capitalState.map(i=><li key={i}>{i}</li>)}</ul></section><section className="hero-architecture-core"><span className="hero-architecture-kicker">02 / Neptlium operating context</span><h2>Preserve meaning across the system.</h2><ol>{operatingCore.map((i,n)=><li key={i}><span>{String(n+1).padStart(2,'0')}</span>{i}</li>)}</ol></section><section className="hero-architecture-plane"><span className="hero-architecture-kicker">03 / Governed work</span><h2>Carry context toward consequence.</h2><ul>{governedWork.map(i=><li key={i}>{i}</li>)}</ul></section></div><p className="hero-system-note">Illustrative operating architecture. No customer financial data shown.</p></div></section>
<section className="operating-environment" aria-labelledby="environment-title"><div className="web-shell editorial-grid"><div><p className="web-eyebrow on-light">The operating problem</p><h2 id="environment-title">Capital should remain intelligible as it moves.</h2></div><div className="editorial-copy"><p>Portfolio state, liquidity, movement, allocation and governance are often divided across tools that preserve only part of the operating picture. The result is not simply fragmented data; it is fragmented meaning.</p><p>Neptlium is designed to reduce the distance between knowing where capital stands, understanding what matters, modeling what may change, reviewing decisions and moving forward with the appropriate authority and context.</p><Link className="text-arrow-link" href="/platform">Understand the operating model <ArrowRight aria-hidden="true" /></Link></div></div></section>
<section className="capital-organization" aria-labelledby="products-title"><div className="web-shell"><header className="section-heading system-heading"><p className="web-eyebrow on-light">Products</p><h2 id="products-title">Defined responsibilities. Shared operating context.</h2><p>Each product carries a distinct part of capital state. The system becomes coherent when those responsibilities can inform one another without borrowing authority from one another.</p></header><div className="capability-system">{PRODUCTS.slice(0,4).map((p,i)=><Link className="capability-row" href={p.href} key={p.href}><span className="capability-index">{String(i+1).padStart(2,'0')}</span><div className="capability-copy"><h3>{p.label}</h3><p>{p.description}</p></div><span className="capability-signal">Product</span><ArrowRight aria-hidden="true" /></Link>)}</div><div className="section-followup"><Link className="text-arrow-link" href="/products">Explore products <ArrowRight aria-hidden="true" /></Link></div></div></section>
<section className="homepage-solutions" aria-labelledby="solutions-title"><div className="web-shell architecture-split"><div><p className="web-eyebrow">Solutions</p><h2 id="solutions-title">Start with the operating ambiguity that needs to be resolved.</h2><p>Neptlium addresses situations where capital visibility, treasury coordination, allocation and control lose context across separate systems and handoffs.</p><Link className="text-arrow-link on-dark" href="/solutions">Explore solutions <ArrowRight aria-hidden="true" /></Link></div><div className="homepage-solution-list">{SOLUTIONS.slice(0,3).map((s,i)=><Link href={s.href} key={s.href}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{s.label}</h3><p>{s.description}</p></div><ArrowRight aria-hidden="true" /></Link>)}</div></div></section>
<section className="intelligence-section" aria-labelledby="truth-title"><div className="web-shell intelligence-grid"><div className="intelligence-heading"><p className="web-eyebrow">Intelligence, governance and trust</p><h2 id="truth-title">Clarity before consequence.</h2><p>Useful financial context depends on preserving the difference between evidence, interpretation, intent, authority and outcome.</p></div><div className="intelligence-list">{trustLayers.map(([title,copy],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}<div className="intelligence-links"><Link href="/security">Security</Link><Link href="/trust">Trust</Link><Link href="/resources">Resources</Link></div></div></div></section>
<section className="reason-section"><div className="web-shell reason-grid"><p className="web-eyebrow on-light">Why Neptlium exists</p><div><h2>Capital operations need a coherent language for state and authority.</h2><p>Neptlium takes a system-level approach because portfolio context, liquidity, movement and allocation affect one another. The objective is to keep those relationships visible while preserving the boundaries that make financial information trustworthy.</p><div className="inline-links home-company-links"><Link href="/about">About Neptlium</Link><Link href="/company">Company</Link><Link href="/learn">Learn</Link></div></div></div></section>
<section className="final-authority"><div className="web-shell final-authority-inner"><div><p className="web-eyebrow">Neptlium</p><h2>Keep the capital picture connected.</h2></div><div><p className="authority-hero-lead">Enter Neptlium or continue through the public architecture to understand the products, operating model and boundaries in more depth.</p><div className="authority-actions"><Link className="web-button primary" href={SITE.publicAccessUrl}>{SITE.publicAccessLabel} <ArrowRight aria-hidden="true" /></Link><Link className="text-arrow-link on-dark" href="/platform">Explore platform <ArrowRight aria-hidden="true" /></Link></div></div></div></section></div>}
