import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, Eye, Fingerprint, History, KeyRound, Layers3, LockKeyhole, Network, ScanSearch, ShieldCheck, SlidersHorizontal } from 'lucide-react'
import { ProductStage } from '@/components/product-stage'
import { Reveal } from '@/components/reveal'
import { SITE } from '@/lib/content/site'
export const metadata:Metadata={title:'Capital, organized around you',description:SITE.description,alternates:{canonical:'/'}}
const capabilities=[['Portfolio Intelligence','Connected sources required',ScanSearch],['Neptlium Wallet','Provider not connected',KeyRound],['Treasury','Backend required',Layers3],['Allocation','Observed allocation unavailable',SlidersHorizontal],['Capital Activity','No transaction history',History]] as const
const questions=['Where is capital currently positioned?','How is it classified?','What is liquid or concentrated?','What is available or planned?','What changes under another allocation model?'] as const
const controls=[['Authenticated access',Fingerprint],['Role-aware boundaries',ShieldCheck],['Provider verification',Network],['Controlled execution',LockKeyhole]] as const
export default function HomePage(){return <>
<section className="hero"><div className="hero-field" aria-hidden="true"><div className="hero-grid"/><div className="orbit one"/><div className="orbit two"/><div className="flow-line flow-one"/><div className="flow-line flow-two"/><div className="hero-core"><span/></div><div className="hero-glow"/></div><div className="hero-inner"><p className="eyebrow">Capital operating infrastructure</p><h1>Capital, organized around you.</h1><p className="hero-copy">{SITE.description}</p><div className="hero-actions"><a className="button" href={SITE.accessUrl}>Access Neptlium <ArrowRight aria-hidden="true"/></a><Link className="text-link" href="/platform">Explore the platform <ArrowRight aria-hidden="true"/></Link></div></div><p className="hero-note">Observe clearly · Model deliberately · Authorize explicitly</p></section>
<section className="section operating-section"><Reveal><div className="section-lead"><p className="eyebrow">Operating environment</p><h2>One coherent view of modern ownership.</h2><p>Understand capital through connected context, model changes without moving assets, and keep operations inside explicit infrastructure boundaries.</p></div></Reveal><Reveal className="operating-frame"><div className="interface-top"><span>Neptlium / Operating environment</span><span className="status">Illustrative</span></div><div className="operating-body"><div className="operating-map" aria-hidden="true"><span/></div><div className="capability-list">{capabilities.map(([name,state,Icon],i)=><div key={name}><span>0{i+1}</span><Icon aria-hidden="true"/><p>{name}</p><small>{state}</small></div>)}</div></div></Reveal></section>
<section className="section visibility-section"><Reveal><div className="visibility-layout"><div className="section-lead"><p className="eyebrow">Capital visibility</p><h2>Better questions before consequential action.</h2><p>Neptlium is structured to make capital legible without manufacturing answers when source data is absent.</p></div><ol>{questions.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></div></Reveal></section>
<section className="section steps"><Reveal><div className="section-lead"><p className="eyebrow">Decision architecture</p><h2>Observe. Model. Authorize.</h2></div></Reveal><div className="step-grid">{[[Eye,'Observe','Observed allocation depends on connected portfolio and custody data.'],[SlidersHorizontal,'Model','Explore non-persistent scenarios to understand possible structural changes.'],[LockKeyhole,'Authorize','Authorization requires real ledger, custody, security and execution infrastructure.']].map(([Icon,title,body],i)=><Reveal key={String(title)}><article><span>0{i+1}</span><Icon aria-hidden="true"/><h3>{String(title)}</h3><p>{String(body)}</p>{i===1&&<strong>Modeling does not move capital.</strong>}{i===2&&<strong>Authorization unavailable</strong>}</article></Reveal>)}</div></section>
<section className="section universe"><Reveal><div className="section-lead"><p className="eyebrow">Capital Universe</p><h2>A focused, provider-dependent foundation.</h2><p>Planned scope is technical intent, not production availability.</p></div></Reveal><div className="asset-row">{[['USDC','Base'],['ETH','Base'],['BTC','Bitcoin']].map(([asset,network],i)=><Reveal key={asset}><article><span>0{i+1}</span><div><h3>{asset}</h3><p>{network}</p></div><ul><li>Planned</li><li>Provider-dependent</li><li>Not currently available</li></ul></article></Reveal>)}</div></section>
<section className="section treasury-section"><Reveal><div className="treasury-layout"><div className="section-lead"><p className="eyebrow">Treasury and readiness</p><h2>Readiness is different from custody.</h2><p>Wallet describes provider-dependent asset infrastructure. Treasury describes liquidity, reserves, exposure and capital readiness. Neither is represented as connected here.</p></div><div className="readiness-panel">{[['Liquidity','Backend required'],['Reserve position','Unavailable'],['Capital readiness','Provider not connected'],['Exposure','Data unavailable']].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></div></Reveal></section>
<section className="section security-block"><Reveal><div className="section-lead"><p className="eyebrow">Security and control</p><h2>Control is part of the architecture.</h2><p>Identity, row-level access, server-side privilege, auditability, provider verification and idempotency are distinct infrastructure boundaries.</p></div></Reveal><div className="control-grid">{controls.map(([x,Icon])=><Reveal key={x}><div><Icon aria-hidden="true"/><span>{x}</span></div></Reveal>)}</div><p className="qualifier">Principles only. No certification, regulatory approval, custody readiness or security guarantee is claimed.</p></section>
<ProductStage/>
<section className="section research-section"><Reveal><div className="research-layout"><div className="section-lead"><p className="eyebrow">Research direction</p><h2>Infrastructure for longer-term decision quality.</h2><p>Our research direction considers capital structure, allocation behavior, operational risk, digital-asset infrastructure and ownership systems.</p></div><div className="research-index"><span>Operating principles</span><span>Research notes</span><span>Capital structure</span><span>Ownership systems</span><Link href="/research">Explore the direction <ArrowRight aria-hidden="true"/></Link></div></div></Reveal></section>
<section className="final-cta"><Reveal><p className="eyebrow">Neptlium</p><h2>Capital deserves an operating environment.</h2><p>Build understanding before action, and keep control explicit.</p><div className="final-actions"><a className="button" href={SITE.accessUrl}>Access Neptlium <ArrowRight aria-hidden="true"/></a><Link className="text-link" href="/contact">Contact <ArrowRight aria-hidden="true"/></Link></div></Reveal></section>
</>}
