import { Section, Stack } from '@neptlium/ui';
import { requireProvisionedUser } from '@/lib/auth';
import { getAccountSettings } from '@/lib/api/client';
import { getTheses } from '@/lib/api/thesis';
import { getThesisAlignment } from '@/lib/api/thesis-revealed';
import { ProductStateMessage } from '@/components/product/ProductState';
import { MfaEnrollment } from './MfaEnrollment';

const EVENT_LABELS: Record<string, string> = { login: 'Signed in', logout: 'Signed out', signup: 'Account created', password_updated: 'Password changed', mfa_enrolled: 'Authenticator app enrolled', mfa_unenrolled: 'Authenticator app removed', sessions_revoked: 'Other sessions signed out' };
const displayValue = (value: string | null | undefined, fallback = 'Not provided') => value?.trim() ? value : fallback;
const strategyLabel = (value: string) => value.toLowerCase().replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const metricLabel = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const relationshipLabel = (value: string) => ({ ALIGNED: 'Aligned with stated thesis', REVEALED_STRICTER: 'Revealed stricter than stated', REVEALED_LOOSER: 'Revealed looser than stated', UNSTATED_PREFERENCE: 'Not currently in stated thesis', CONTRADICTORY: 'Contradicts stated criterion', INSUFFICIENT_HISTORY: 'Insufficient decision history' }[value] ?? value);
const observationLabel = (observation: { observationType: string; derivedOperator?: string; derivedValue?: number | string }) => {
  if (typeof observation.derivedValue === 'number') return `${observation.derivedOperator === 'LTE' ? 'At or below' : 'At or above'} approximately ${observation.derivedValue.toFixed(1)}`;
  if (typeof observation.derivedValue === 'string') return `${observation.observationType === 'NEGATIVE_ASSOCIATION' ? 'Negative' : 'Positive'} association with ${observation.derivedValue}`;
  return observation.observationType === 'POSITIVE_ASSOCIATION' ? 'Strong positive association' : observation.observationType === 'NEGATIVE_ASSOCIATION' ? 'Strong negative association' : observation.observationType.replaceAll('_', ' ').toLowerCase();
};

export default async function SettingsPage() {
  await requireProvisionedUser();
  const [settingsResult, thesisResult] = await Promise.allSettled([getAccountSettings(), getTheses()]);
  const settings = settingsResult.status === 'fulfilled' ? settingsResult.value : null; const thesisState = thesisResult.status === 'fulfilled' ? thesisResult.value : null; const thesisBundle = thesisState?.data.find((item) => item.thesis.isDefault) ?? thesisState?.data[0] ?? null;
  const alignmentResult = thesisBundle ? await getThesisAlignment(thesisBundle.thesis.id).catch(() => null) : null;
  return <Stack>
    <header><h1>Settings</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-text-muted">Profile, institutional decision context, security, and account preferences.</p></header>
    <Section title="Profile"><div className="border-y border-border-hairline py-5">{settings ? <dl className="grid gap-x-10 gap-y-5 sm:grid-cols-2"><SettingValue label="Name" value={displayValue(settings.profile.fullName ?? settings.profile.displayName)} /><SettingValue label="Email" value={displayValue(settings.profile.email)} /><SettingValue label="Account purpose" value={displayValue(settings.profile.investorType, 'Not configured')} /><SettingValue label="Compliance status" value={displayValue(settings.profile.complianceStatus, 'Not configured')} capitalize /></dl> : <ProductStateMessage state="ERROR" title="Account settings could not be loaded">The Neptlium API did not return profile settings.</ProductStateMessage>}</div></Section>
    {settings?.organization ? <Section title="Organization"><dl className="grid gap-x-10 gap-y-5 border-y border-border-hairline py-5 sm:grid-cols-2"><SettingValue label="Company name" value={displayValue(settings.organization.name)} /><SettingValue label="Your role" value={displayValue(settings.organization.role)} /><SettingValue label="Industry" value={displayValue(settings.organization.industry)} /><SettingValue label="Country" value={displayValue(settings.organization.country)} /><SettingValue label="Organization size" value={displayValue(settings.organization.organizationSize)} />{settings.organization.aumRange ? <SettingValue label="Reported AUM range" value={settings.organization.aumRange} /> : null}</dl></Section> : null}
    <Section title="Investment thesis"><div className="border-y border-border-hairline py-5">{thesisState === null ? <ProductStateMessage state="ERROR" title="Thesis state could not be loaded">The Neptlium API did not return the institutional thesis state.</ProductStateMessage> : thesisBundle ? <div><p className="neptlium-meta">Stated thesis</p><div className="mt-3 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium text-text-primary">{thesisBundle.thesis.name}</p><p className="mt-1 text-sm text-text-muted">{strategyLabel(thesisBundle.thesis.strategy)} · Version {thesisBundle.thesis.version}</p></div><span className="text-xs text-text-muted">{thesisBundle.criteria.length} governed {thesisBundle.criteria.length === 1 ? 'criterion' : 'criteria'}</span></div><dl className="mt-5 grid gap-x-10 gap-y-5 sm:grid-cols-2"><SettingValue label="Sectors" value={thesisBundle.thesis.sectors.length ? thesisBundle.thesis.sectors.join(', ') : 'Unrestricted'} /><SettingValue label="Geographies" value={thesisBundle.thesis.geographies.length ? thesisBundle.thesis.geographies.join(', ') : 'Unrestricted'} /></dl><p className="mt-5 max-w-2xl text-xs leading-5 text-text-muted">This remains the authoritative governed mandate. Revealed Thesis observations never modify it automatically.</p></div> : <ProductStateMessage state="NO_ACTIVITY" title="No investment thesis configured">The current API response contains no governed thesis.</ProductStateMessage>}</div>
      {thesisBundle ? <div className="border-b border-border-hairline py-6"><div className="mb-5"><p className="neptlium-meta">Revealed thesis</p><p className="mt-2 max-w-2xl text-sm leading-6 text-text-muted">Observed only from explicit historical Thesis decisions and their immutable evaluation snapshots. Patterns are surfaced only when deterministic support, separation, and confidence thresholds are met.</p></div>{!alignmentResult || alignmentResult.state === 'INSUFFICIENT_HISTORY' ? <ProductStateMessage state="NO_ACTIVITY" title="Insufficient decision history">No current-version behavioral pattern has enough governed evidence to surface yet.</ProductStateMessage> : <div className="divide-y divide-border-hairline border-y border-border-hairline">{alignmentResult.data.map((item) => <div key={item.metricKey} className="grid gap-3 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><p className="text-sm font-medium text-text-primary">{metricLabel(item.metricKey)}</p><p className="mt-1 text-sm text-text-secondary">{item.revealedObservation ? observationLabel(item.revealedObservation) : 'No meaningful revealed pattern'}</p><p className="mt-1 text-xs text-text-muted">{relationshipLabel(item.relationship)}</p></div><div className="text-left sm:text-right"><p className="text-sm font-medium tabular-nums text-text-primary">{Math.round(item.confidenceBps / 100)}%</p><p className="mt-1 text-xs text-text-muted">Confidence</p></div></div>)}</div>}</div> : null}
    </Section>
    <Section title="Security"><div className="divide-y divide-border-hairline border-y border-border-hairline"><div className="py-5"><p className="text-sm font-medium text-text-primary">Multi-factor authentication</p><p className="mt-1 mb-4 text-sm text-text-muted">Manage Clerk authentication, passkeys, multi-factor authentication, and active sessions.</p><MfaEnrollment /></div></div></Section>
    <Section title="Recent security activity"><div className="border-y border-border-hairline">{settings === null ? <ProductStateMessage state="ERROR" title="Security activity could not be loaded" /> : settings.securityActivity.length ? settings.securityActivity.map((event) => <div key={event.id} className="flex flex-col gap-1 border-b border-border-hairline py-4 text-sm last:border-0 sm:flex-row sm:items-center sm:justify-between sm:gap-6"><span className="text-text-primary">{EVENT_LABELS[event.eventType] ?? event.eventType}</span><time className="text-xs text-text-muted" dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString()}</time></div>) : <ProductStateMessage state="NO_ACTIVITY" title="No recorded security activity yet" />}</div></Section>
  </Stack>;
}
function SettingValue({ label, value, capitalize = false }: { readonly label: string; readonly value: string; readonly capitalize?: boolean }) { return <div><dt className="text-xs text-text-muted">{label}</dt><dd className={`mt-1.5 text-sm font-medium text-text-primary ${capitalize ? 'capitalize' : ''}`}>{value}</dd></div>; }
