export type ErrorCode =
  | 'authentication_required'
  | 'authentication_unavailable'
  | 'forbidden'
  | 'admin_forbidden'
  | 'admin_storage_unavailable'
  | 'admin_data_unavailable'
  | 'admin_role_ambiguous'
  | 'admin_delegation_disabled'
  | 'admin_route_not_found'
  | 'role_state_ambiguous'
  | 'super_admin_protected'
  | 'role_update_failed'
  | 'compliance_update_failed'
  | 'audit_unavailable'
  | 'deposit_completion_unavailable'
  | 'withdrawal_approval_unavailable'
  | 'withdrawal_rejection_unavailable'
  | 'allocation_authorization_unavailable'
  | 'validation_failed'
  | 'payload_too_large'
  | 'rate_limited'
  | 'rate_limit_unavailable'
  | 'not_found'
  | 'data_unavailable'
  | 'account_not_provisioned'
  | 'invalid_state_transition'
  | 'invalid_funding_transition'
  | 'invalid_transfer_transition'
  | 'invalid_allocation_transition'
  | 'invalid_canonical_balance'
  | 'idempotency_conflict'
  | 'idempotency_key_required'
  | 'provider_not_configured'
  | 'provider_unavailable'
  | 'provider_capability_unavailable'
  | 'provider_submission_failed'
  | 'provider_response_invalid'
  | 'provider_environment_mismatch'
  | 'provider_reference_unavailable'
  | 'provider_wallet_unavailable'
  | 'provider_wallet_not_linked'
  | 'provider_wallet_conflict'
  | 'provider_execution_disabled'
  | 'provider_execution_unimplemented'
  | 'live_execution_disabled'
  | 'financial_storage_unavailable'
  | 'allocation_storage_unavailable'
  | 'allocation_conflict'
  | 'allocation_validation_failed'
  | 'allocation_policy_invalid'
  | 'allocation_target_total_invalid'
  | 'allocation_policy_not_authorized'
  | 'allocation_reservation_invalid'
  | 'stale_policy_version'
  | 'restricted_asset'
  | 'unsupported_asset'
  | 'insufficient_available_capital'
  | 'canonical_operation_failed'
  | 'webhook_inbox_unavailable'
  | 'settlement_evidence_unavailable'
  | 'deposit_attribution_unavailable'
  | 'reconciliation_unavailable'
  | 'alias_conflict'
  | 'destination_not_verified'
  | 'unsupported_capability'
  | 'route_replaced'
  | 'invalid_webhook'
  | 'webhook_replay_detected'
  | 'insufficient_funds'
  | 'internal_error';
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly code: ErrorCode,
    message: string,
    public readonly details?: unknown,
  ) {
    super(message);
  }
}
