import assert from 'node:assert/strict';
import test from 'node:test';
import { analyzeRevealedThesis, compareStatedAndRevealed, proposeRevealedThesisAdoption } from '../dist/thesis-revealed.js';

const criterion = (metricKey, value, evidenceConfidenceBps = 9000) => ({ criterion: { metricKey, kind: metricKey === 'founder_led' ? 'QUALITATIVE' : 'QUANTITATIVE', operator: metricKey === 'founder_led' ? 'IS_TRUE' : 'GTE', numericValue: 25, weightBps: 1000, importance: 'PREFERRED', position: 0 }, outcome: 'PASS', resolved: { metric: { key: metricKey }, value, evidence: { confidenceBps: evidenceConfidenceBps } }, reason: 'resolved' });
const snapshot = (id, key, values, version = 1) => ({ id, ownerId: 'owner', thesisId: 'thesis', thesisVersion: version, subjectType: 'company', subjectKey: key, decision: 'QUALIFIED', scoreBps: 8000, coverageBps: 10000, confidenceBps: 9000, summary: { decision: 'QUALIFIED', scoreBps: 8000, coverageBps: 10000, confidenceBps: 9000, totalWeightBps: 10000, knownWeightBps: 10000, passedWeightBps: 8000, requiredOutcome: true, criteria: Object.entries(values).map(([k, v]) => criterion(k, v)) }, evaluatedBy: 'owner', evaluatedAt: '2026-09-08T00:00:00Z' });
const decision = (id, key, status, evaluationId, version = 1) => ({ id, ownerId: 'owner', thesisId: 'thesis', thesisVersion: version, subjectType: 'company', subjectKey: key, status, evaluationId, decidedBy: 'owner', decidedAt: `2026-09-0${Math.min(8, Number(id.replace(/\D/g, '')) || 1)}T00:00:00Z` });
function history(pos, neg, metric = 'revenue_growth_yoy') { const evaluations = []; const decisions = []; pos.forEach((value, i) => { const id = `p${i + 1}`; evaluations.push(snapshot(id, id, { [metric]: value })); decisions.push(decision(`d${i + 1}`, id, i % 2 ? 'INVESTED' : 'INTERESTED', id)); }); neg.forEach((value, i) => { const id = `n${i + 1}`; evaluations.push(snapshot(id, id, { [metric]: value })); decisions.push(decision(`d${i + 20}`, id, 'PASS', id)); }); return { evaluations, decisions }; }

test('insufficient and small history fails closed', () => { const h = history([35, 40], [10, 15]); assert.equal(analyzeRevealedThesis({ ownerId: 'owner', thesisId: 'thesis', thesisVersion: 1, ...h }).state, 'INSUFFICIENT_HISTORY'); });
test('strong numeric separation produces a transparent threshold with exact evidence links', () => { const h = history([31, 35, 42, 38, 29, 36], [12, 16, 18, 14, 20, 17]); const result = analyzeRevealedThesis({ ownerId: 'owner', thesisId: 'thesis', thesisVersion: 1, ...h, computedAt: '2026-09-08T01:00:00Z' }); assert.equal(result.state, 'VALUE'); const o = result.observations.find((x) => x.metricKey === 'revenue_growth_yoy'); assert.ok(o); assert.equal(o.derivedOperator, 'GTE'); assert.ok(o.derivedValue > 20 && o.derivedValue < 35); assert.equal(o.evidenceDecisionIds.length, 12); assert.equal(o.evidenceEvaluationIds.length, 12); });
test('contradictions reduce confidence', () => { const clean = analyzeRevealedThesis({ ownerId: 'owner', thesisId: 'thesis', thesisVersion: 1, ...history([35,36,37,38,39,40],[10,11,12,13,14,15]) }); const mixed = analyzeRevealedThesis({ ownerId: 'owner', thesisId: 'thesis', thesisVersion: 1, ...history([35,36,12,38,39,40],[10,34,12,13,14,15]) }); assert.ok(clean.observations[0].confidenceBps > mixed.observations[0].confidenceBps); });
test('missing evidence reduces usable metric sample and unsupported metrics are never invented', () => { const h = history([35,36,37],[10,11,12]); h.evaluations.push(snapshot('x','x',{ mystery_metric: 999 })); h.decisions.push(decision('d99','x','INVESTED','x')); const result = analyzeRevealedThesis({ ownerId:'owner', thesisId:'thesis', thesisVersion:1, ...h }); assert.equal(result.observations.some((x)=>x.metricKey==='mystery_metric'), false); });
test('boolean frequency pattern is detected', () => { const h = history([true,true,true,true,true,false],[false,false,false,false,true,false], 'founder_led'); const result = analyzeRevealedThesis({ ownerId:'owner', thesisId:'thesis', thesisVersion:1, ...h }); assert.equal(result.observations.find((x)=>x.metricKey==='founder_led')?.observationType, 'POSITIVE_ASSOCIATION'); });
test('stated versus revealed stricter, looser and unstated comparisons are deterministic', () => { const base = { id:'c', thesisId:'thesis', metricKey:'revenue_growth_yoy', kind:'QUANTITATIVE', operator:'GTE', numericValue:25, weightBps:1000, importance:'PREFERRED', position:0, createdAt:'x', updatedAt:'x' }; const observation = { id:'o', ownerId:'owner', thesisId:'thesis', thesisVersions:[1], metricKey:'revenue_growth_yoy', observationType:'MINIMUM_THRESHOLD', derivedOperator:'GTE', derivedValue:32, supportCount:5, contradictionCount:1, sampleSize:12, confidenceBps:8000, strengthBps:5000, decisionCohort:'POSITIVE', positiveCohort:{resolvedCount:6}, negativeCohort:{resolvedCount:6}, evidenceEvaluationIds:[], evidenceDecisionIds:[], firstObservedAt:'x', lastObservedAt:'x', computedAt:'x', versionScope:'CURRENT_ONLY' }; assert.equal(compareStatedAndRevealed([base],[observation])[0].relationship,'REVEALED_STRICTER'); assert.equal(compareStatedAndRevealed([{...base,numericValue:40}],[observation])[0].relationship,'REVEALED_LOOSER'); assert.equal(compareStatedAndRevealed([], [observation])[0].relationship,'UNSTATED_PREFERENCE'); });
test('old thesis-version history never masquerades as current behavior and proposals do not mutate stated input', () => { const h = history([35,36,37,38,39,40],[10,11,12,13,14,15]); h.decisions.push(decision('old','old','INVESTED','old',2)); h.evaluations.push(snapshot('old','old',{revenue_growth_yoy:99},2)); const result = analyzeRevealedThesis({ ownerId:'owner', thesisId:'thesis', thesisVersion:1, ...h }); assert.deepEqual(result.observations[0].thesisVersions,[1]); const stated = { id:'c', thesisId:'thesis', metricKey:'revenue_growth_yoy', kind:'QUANTITATIVE', operator:'GTE', numericValue:25, weightBps:1000, importance:'PREFERRED', position:0, createdAt:'x', updatedAt:'x' }; const before = structuredClone(stated); proposeRevealedThesisAdoption(result.observations[0], stated); assert.deepEqual(stated,before); });
