import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { SharedCoreVisual } from '@/components/unified-product-visuals';
import { createPageMetadata } from '@/lib/seo';
import styles from '../unified-marketing.module.css';

export const metadata = createPageMetadata({
  title: 'Company — Neptlium',
  description: 'Neptlium, a Neptliumforge company, builds financial systems across personal capital, business treasury, institutional operations and infrastructure with clear authority, evidence and reconciliation.',
  path: '/company',
});

export default function CompanyPage() {
  return <div className={styles.page}>
    <section className={styles.journeyHero} data-npt-surface="ivory" aria-labelledby="company-title"><div className={styles.shell}><div className={styles.heroCopy}><p className={styles.eyebrow}>A Neptliumforge company</p><h1 id="company-title">Financial systems for capital that needs to move with clarity.</h1><p className={styles.heroLead}>Individuals need better capital visibility. Businesses need better treasury control. Institutions need stronger operating controls. All require clear authority, reliable evidence, reconciliation and explainable financial state.</p></div></div></section>
    <section className={styles.section} data-npt-surface="white" aria-labelledby="company-thesis-title"><div className={styles.shell}><div className={styles.sectionHead}><p className={styles.eyebrow}>Company thesis</p><div><h2 id="company-thesis-title">One Neptlium platform across capital, treasury, institutional operations and infrastructure.</h2><p>Neptlium Capital serves individual investors. Neptlium Treasury serves business treasury teams. Neptlium Institutional is the long-term institutional pillar. Neptlium Infrastructure connects Pay, API, Docs and Status. The product experiences differ because the work differs; the financial-control principles remain shared. Neptlium operates within parent company Neptliumforge.</p></div></div><div className={styles.journeyGrid}><article className={styles.journeyCard}><span>Capital</span><h3>Capital clarity for investors.</h3><p>Capital, portfolio, allocation, investment context, activity and reporting.</p><Link className={styles.textAction} href="/personal">Explore Neptlium Capital <ArrowRight aria-hidden="true" /></Link></article><article className={styles.journeyCard}><span>Treasury</span><h3>Treasury control for teams.</h3><p>Treasury, payments, approvals, policies, risk, reconciliation and audit.</p><Link className={styles.textAction} href="/business">Explore Neptlium Treasury <ArrowRight aria-hidden="true" /></Link></article></div></div></section>
    <section className={`${styles.section} ${styles.ivory}`} data-npt-surface="cloud" aria-labelledby="company-system-title"><div className={styles.shell}><div className={styles.sectionHead}><p className={styles.eyebrow}>System philosophy</p><div><h2 id="company-system-title">Financial consequence should always be explainable.</h2><p>Neptlium is designed around explicit state, controlled authority, durable evidence and reconciliation rather than optimistic status labels or hidden financial assumptions.</p></div></div><div data-npt-product-canvas="dark"><SharedCoreVisual /></div></div></section>
    <section className={styles.section} data-npt-surface="mineral" aria-labelledby="company-direction-title"><div className={styles.shell}><div className={styles.sectionHead}><p className={styles.eyebrow}>Long-term direction</p><div><h2 id="company-direction-title">Build a coherent operating environment for modern capital.</h2><p>Neptlium’s direction is to make financial state understandable across personal, business and institutional use cases while preserving explicit authority and infrastructure boundaries without fabricating scale, licensing, partnerships or product availability.</p><Link className={styles.textAction} href="/contact">Contact Neptlium <ArrowRight aria-hidden="true" /></Link></div></div></div></section>
  </div>;
}
