import Link from 'next/link';
import { ArrowRight } from 'lucide-react';
import { COMPANY } from '@/lib/content/public-architecture';
import { createPageMetadata } from '@/lib/seo';

export const metadata=createPageMetadata({title:'Company — Neptlium',description:'Neptlium is building a capital operating platform around connected context, explicit authority and disciplined representation of financial state.',path:'/company'});
const principles=[
 ['Capital should remain intelligible','The company exists to reduce fragmentation between knowing where capital stands, understanding what matters, modeling what may change and governing what happens next.'],
 ['State should remain truthful','Observed, provider-reported, modeled, proposed, authorized and consequential information should retain the distinctions that give it meaning.'],
 ['Authority should be explicit','Identity, review, permission and financial consequence belong in the operating architecture, not in implied trust or ambiguous interface language.'],
 ['Boundaries should be communicated','Neptlium should describe what the platform provides, what depends on external providers and what remains unavailable without inventing authority, certainty or institutional credentials.'],
] as const;
export default function CompanyPage(){return <div className="architecture-page company-hub"><section className="architecture-hero"><div className="web-shell architecture-hero-grid"><div><p className="web-eyebrow on-light">Company</p><h1>Building an operating system for capital.</h1></div><div className="architecture-lead"><p>Neptlium is focused on a structural problem in capital operations: important context is often divided between portfolio views, liquidity, movement, allocation and governance systems that do not preserve each other’s state.</p><p>The company is building a coherent operating environment for that work, with particular emphasis on financial meaning, authority boundaries and responsible representation.</p></div></div></section><section className="architecture-section" aria-labelledby="principles-title"><div className="web-shell architecture-split"><div><p className="web-eyebrow on-light">Principles</p><h2 id="principles-title">The company should operate with the same discipline the product requires.</h2></div><div className="architecture-numbered-list">{principles.map(([title,body],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></div></section><section className="architecture-section architecture-dark"><div className="web-shell"><div className="architecture-section-heading"><p className="web-eyebrow">Company information</p><h2>Institutional information, without manufactured corporate mythology.</h2></div><div className="architecture-link-list dark-links">{COMPANY.map((d,index)=><Link href={d.href} key={d.href}><span>{String(index+1).padStart(2,'0')}</span><div><h3>{d.label}</h3><p>{d.description}</p></div><ArrowRight aria-hidden="true" /></Link>)}</div></div></section><section className="architecture-cta"><div className="web-shell architecture-cta-inner"><h2>Read the thesis behind the platform.</h2><Link className="web-button primary" href="/about">About Neptlium <ArrowRight aria-hidden="true" /></Link></div></section></div>}
